### ISSUE TITLE
pointBackgroundColor

### ISSUE THREAD

**Issue by XYStore** [hackjie/GPassword#1]
option.pointBackgroundColor = UIColor.red 不起作用

**Comment by hackjie** [comment]
抱歉，这个属性确实没加上，你能简单画个图说明你想要的 未选中 和 选中的效果图么

**Comment by XYStore** [comment]
还有一个问题就是设置密码的存储方式 public var storeType: StoreType = .userDefault, 设置之后手势密码选中的效果看不到了，我是这样设置的 option.storeType = .userDefault，请问是不是还需要设置什么

**Comment by hackjie** [comment]
@XYStore 看不到选中效果，应该是你把显示跟踪轨迹关闭了，控制这个开关也会存在本地的
```
GPassword.openTrack()
```

**Comment by hackjie** [comment]
@XYStore 我处理了下你说的两个问题，你试下 1.0.8 版本，感谢反馈！
